{% set name = "pyinaturalist" %}
{% set version = "0.15.0" %}
{% set hash_val = "a31f1280acead75a6d13823436ef4f56edeb5bc79cd8f79e9622b6fcc3045309" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - poetry
    - pip
  run:
    - python >=3.6
    - appdirs >=1.4
    - attrs >=21.2
    - keyring >=22.3
    - python-dateutil >=2.0
    - python-forge >=18.6.0
    - requests >=2.20
    - requests-cache >=0.7.4
    - requests-ratelimiter >=0.2
    - rich >=10.0

test:
  imports:
    - pyinaturalist
    - pyinaturalist.controllers
    - pyinaturalist.docs
    - pyinaturalist.models
    - pyinaturalist.v0
    - pyinaturalist.v1
    - pyinaturalist.v2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/niconoe/pyinaturalist
  summary: Python API client for iNaturalist
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io/
  dev_url: https://github.com/niconoe/pyinaturalist

extra:
  recipe-maintainers:
    - jwcook
