{% set name = "pyinaturalist" %}
{% set version = "0.21.0" %}
{% set hash_val = "f15c08703746e3aa61bbbe35fe1c79901693c9d737c1d74a449a003d4a8bb8e1" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - attrs >=21.2
    - keyring >=22.3
    - platformdirs >=2.5
    - python-dateutil >=2.0
    - requests >=2.25
    - requests-cache >=1.2
    - requests-ratelimiter >=0.5.1
    - rich >=10.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pyinaturalist
    - pyinaturalist.controllers
    - pyinaturalist.docs
    - pyinaturalist.models
    - pyinaturalist.v0
    - pyinaturalist.v1
    - pyinaturalist.v2

about:
  home: https://github.com/pyinat/pyinaturalist
  summary: Python API client for iNaturalist
  license: MIT
  license_file: LICENSE
  doc_url: https://pyinaturalist.readthedocs.io
  dev_url: https://github.com/pyinat/pyinaturalist

extra:
  recipe-maintainers:
    - jwcook
